import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import NavigationButton from "@/components/buttons/NavigationButton";
import AnimatedTitle from "@/components/typography/AnimatedTitle";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export type NavigationLink = {
    href: string;
    title: string;
}

const navigation_links: NavigationLink[] = [
    {
        href: "/collection",
        title: "Film collection"
    },
    {
        href: "/showings",
        title: "Showings"
    },
    {
        href: "/about",
        title: "About northg8"
    }
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={dosis.className}>
                <div className="flex w-full">
                    <div className="w-1/2">
                        {children}
                    </div>
                    <div className="fixed left-1/2 flex flex-col w-1/2 h-screen border-typography-black border-l">
                        <div className="flex justify-center items-center w-full h-1/2 border-typography-black border-b">
                            <AnimatedTitle />
                        </div>
                        <div className="flex flex-col w-full h-1/2 justify-center">
                            {
                                navigation_links.map((link, idx) => (
                                    <NavigationButton key={idx} href={link.href} title={link.title} />
                                ))
                            }                         
                        </div>
                    </div>
                </div>
            </body>
        </html>
    );
}
