import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "../globals.css";
import { Providers } from "@/components/providers/Providers";
import { auth } from "@/auth";

const dosis = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();

    return (
        <html lang="en">
            <body className={dosis.className}>
                <Providers session={session}>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
